version: '3.4'

services:
  postgressql:
    platform: linux/x86_64
    restart: unless-stopped
    container_name: postgressql_multimedia_retrieval
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE='postgres'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    deploy:
      resources:
        limits:
          memory: 1gb
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  db-data: